

spring:
  application:
    name: product-data-service
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://www.haskie.cn:8761/eureka/
server:
  port: 8002
