

spring:
  application:
    name: product-data-service
  zipkin:
    base-url: http:///www.haskie.cn:9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://www.haskie.cn:8761/eureka/
server:
  port: 8003 #因为会启动多个 product-data-service, 所以端口号由用户自动设置，推荐 8001,8002,8003
