server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: www.haskie.cn
  client:
    registerWithEureka: false #表示是否注册到服务器。 因为它本身就是服务器，所以就无需把自己注册到服务器了。
    fetchRegistry: false #表示是否获取服务器的注册信息，和上面同理，这里也设置为 false。
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #公布出来的地址。 比如后续某个微服务要把自己注册到 eureka server, 那么就要使用这个地址： http://www.haskie.cn:8761/eureka/

