
server:
  port: 8030

spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/gitcjj96/springcloudConfig
          searchPaths: respo
eureka:
  client:
    serviceUrl:
      defaultZone: http://www.haskie.cn:8761/eureka/