
server:
  port: 8030

spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/gitcjj96/springcloudConfig    # 配置git仓库的地址
          searchPaths: respo                                    # git仓库地址下的相对地址，可以配置多个，用,分割。
          username:                                             # git仓库的账号
          password:                                             # git仓库的密码
eureka:
  client:
    serviceUrl:
      defaultZone: http://www.haskie.cn:8761/eureka/